### ISSUE TITLE
CNN_ALL

### ISSUE THREAD

**Issue by ZZSOGAZ** [k-papadakis/geospatial-labs#2]
I want to change the patch size of CNN =5.
But RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x64 and 576x128)

**Comment by k-papadakis** [comment]
Hi!
This is because the final block (`self.classifier`) expects a 64 x 3 x 3 tensor. If you change the patch size from 15 x 15 to 5 x 5, then the tensor that `self.classifier` receives is going to be 64 x 1 x 1.

Why does this happen? It's because each of the maxpooling layers are shrinking the image by a factor of 2 (floor division by 2).

So, for the 15 x 15 case we have

* maxpool1 result: 15 // 2 = 7
* maxpool2 result: 7 // 2 = 3

While in the 5 x 5 case we have

* 5 // 2 = 2
* 2 // 2 = 1

You can change `nn.Linear(3 * 3 * 64, 128)` to `nn.Linear(1 * 1 * 64, 128)` and it will work.

Another solution, which doesn't reduce the image to a single pixel, would be to remove block2 and the second maxpool

```python
    def forward(self, x):
        x = self.stem(x)
        x = x + self.block1(x)
        x = F.max_pool2d(x, kernel_size=2, stride=2)
        # x = x + self.block2(x)
        # x = F.max_pool2d(x, kernel_size=2, stride=2)
        x = x + self.block3(x)
        x = self.classifier(x)
        return x
```
and use `nn.Linear(2 * 2 * 64, 128)` in `self.classifier`.

**Comment by ZZSOGAZ** [comment]
Thank you very much for your help! 
I know I may be presumptuous,I have some other questions.

1. The data was replaced with my own data, and when I was training, I had this question:RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.
2. I want to add ndvi and other spectral indices to my feature set, but the data type is double64.What do you suggest?
Thank you again!

**Comment by k-papadakis** [comment]
Glad to be of help!

1. Considering your first question, that error means that `torch.max()` was called on an empty tensor. So, maybe your data has an empty tensor? Empty tensors can be created from slices like a[1:1].

2. To add extra channels, if `cur` is your current channels and `extra` is your new channels, then you can do
```python
merged = np.concatenate([cur, extra], axis=0, dtype=np.float32])
# axis=-1 if channels are in the last dimension
# dtype=your desired output data type
```
Note that if `extra` is a single channel with shape h x w, you will need reshape it into 1 x h x w. This can be done with
```python
extra = np.expand_dims(extra, axis=0)
```

**Comment by ZZSOGAZ** [comment]
@k-papadakis Thank you!
